export default [
  "Itaú Unibanco",
  "Banco do Brasil",
  "Bradesco",
  "Caixa Econômica Federal",
  "Santander Brasil",
  "BTG Pactual",
  "Sicredi",
  "Sicoob",
  "Banco Safra",
  "Citibank Brasil",
  "Banrisul",
  "Banco Votorantim",
  "Banco Inter",
  "Nubank",
  "Nexoos",
  "Neon",
  "Banco Pan",
  "PicPay",
  "C6 Bank",
  "PagBank",
];
